import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateExperienceShare1753856408373 implements MigrationInterface {
    name = 'CreateExperienceShare1753856408373'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "experience_lock" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_activity" TIMESTAMP NOT NULL, "experienceId" integer, "lockedBySub" character varying, CONSTRAINT "REL_574f16ad51edd8132aa3baa404" UNIQUE ("experienceId"), CONSTRAINT "PK_5b896ea2e30fe2e77d9bf7df335" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "experience_type" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cognito_identity_id" character varying NOT NULL, "source_ip" character varying NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_8d5dadc8e5aed9c22371056b255" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "experience_share" ("experience_id" integer NOT NULL, "shared_to_id" character varying NOT NULL, "shared_by_id" character varying NOT NULL, "shared_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c0f21f7d4d1cee8e0c8ed7e38d1" PRIMARY KEY ("experience_id", "shared_to_id", "shared_by_id"))`);
        await queryRunner.query(`CREATE TABLE "tag" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cognito_identity_id" character varying NOT NULL, "source_ip" character varying NOT NULL, "name" character varying NOT NULL, "subSub" character varying, CONSTRAINT "PK_8e4052373c579afc1471f526760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attribute" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cognito_identity_id" character varying NOT NULL, "source_ip" character varying NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_b13fb7c5c9e9dff62b60e0de729" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "experience" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cognito_identity_id" character varying NOT NULL, "source_ip" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying, "privacy" integer NOT NULL, "editable_by_own_org" boolean NOT NULL DEFAULT false, "can_clone" integer DEFAULT '3', "json" json NOT NULL, "date_took_place" TIMESTAMP, "location_lat" double precision, "location_long" double precision, "languages" text, "experienceTypeId" integer, "layoutId" integer, "spaceId" integer, "mediaId" integer, "screenshot1Id" integer, "screenshot2Id" integer, "screenshot3Id" integer, "screenshot4Id" integer, "attachmentId" integer, "subSub" character varying, "organisationId" integer, CONSTRAINT "REL_7095715562d576a66b277f9d51" UNIQUE ("screenshot1Id"), CONSTRAINT "REL_938785766ad154f3ed70586dae" UNIQUE ("screenshot2Id"), CONSTRAINT "REL_ded1e2268c84d94743cf60d875" UNIQUE ("screenshot3Id"), CONSTRAINT "REL_cf37c077b800be33d6f19b7420" UNIQUE ("screenshot4Id"), CONSTRAINT "REL_1998a5b58df53b9f44c17ae91b" UNIQUE ("attachmentId"), CONSTRAINT "PK_5e8d5a534100e1b17ee2efa429a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("sub" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "given_name" character varying NOT NULL, "family_name" character varying NOT NULL, "disabled" boolean NOT NULL DEFAULT false, "preferences" jsonb, "mediaId" integer, CONSTRAINT "REL_cd81db2b14bf99eaec0934d1f2" UNIQUE ("mediaId"), CONSTRAINT "PK_3641ff83ff7c23b2760b3df56d4" PRIMARY KEY ("sub"))`);
        await queryRunner.query(`CREATE TABLE "surface" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cognito_identity_id" character varying NOT NULL, "source_ip" character varying NOT NULL, "position" integer NOT NULL, "dimensions" character varying NOT NULL, "wide" boolean NOT NULL, "physicalAspectRatio" double precision, "surfaceDivisions" integer, "subSub" character varying, "layoutId" integer, CONSTRAINT "PK_51afeb91d3c7e6977caa2a25a53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "layout" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cognito_identity_id" character varying NOT NULL, "source_ip" character varying NOT NULL, "name" character varying NOT NULL, "subSub" character varying, "mediaId" integer, CONSTRAINT "REL_9b074878ef04eb6067e8650d23" UNIQUE ("mediaId"), CONSTRAINT "PK_6e288ce489327c1ec1274d24942" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "space" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cognito_identity_id" character varying NOT NULL, "source_ip" character varying NOT NULL, "name" character varying NOT NULL, "layoutId" integer, "subSub" character varying, "organisationId" integer, "mediaId" integer, CONSTRAINT "REL_c8af3f4482bdc5cacfb808a046" UNIQUE ("mediaId"), CONSTRAINT "PK_094f5ec727fe052956a11623640" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "organisation" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cognito_identity_id" character varying NOT NULL, "source_ip" character varying NOT NULL, "name" character varying NOT NULL, "can_delete" boolean NOT NULL DEFAULT true, "max_users" integer, "show_bespoke" boolean NOT NULL DEFAULT false, "require_mfa" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_d9428f9c8e3052d6617e3aab0ed" UNIQUE ("name"), CONSTRAINT "PK_c725ae234ef1b74cce43d2d00c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "media" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cognito_identity_id" character varying NOT NULL, "source_ip" character varying NOT NULL, "filename" character varying, "original_filename" character varying NOT NULL, "extension" character varying NOT NULL, "subSub" character varying, "organisationId" integer, CONSTRAINT "PK_f4e0fcac36e050de337b670d8bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "template_file" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cognito_identity_id" character varying NOT NULL, "source_ip" character varying NOT NULL, "name" character varying NOT NULL, "fileId" integer, "subSub" character varying, CONSTRAINT "REL_908ab0a2e22b2aba67244a45f2" UNIQUE ("fileId"), CONSTRAINT "PK_81e5525c05f228a8279927e8c37" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "template" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cognito_identity_id" character varying NOT NULL, "source_ip" character varying NOT NULL, "name" character varying NOT NULL, "editorDirectory" character varying, "type" character varying NOT NULL, "hasHotspots" boolean NOT NULL DEFAULT false, "defaultConfig" json NOT NULL, "version" character varying(100), "disabled" boolean NOT NULL DEFAULT false, "featured" boolean, "thumbnailId" integer, "templateFileId" integer, "fileId" integer, "subSub" character varying, CONSTRAINT "REL_678a3f1beca5c93db880148d90" UNIQUE ("thumbnailId"), CONSTRAINT "REL_0c66ef16947cecf8e029a07718" UNIQUE ("fileId"), CONSTRAINT "PK_fbae2ac36bd9b5e1e793b957b7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "asset_tag" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cognito_identity_id" character varying NOT NULL, "source_ip" character varying NOT NULL, "name" character varying NOT NULL, "subSub" character varying, CONSTRAINT "PK_bc1024247786d70ae36c809e1ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "asset" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "cognito_identity_id" character varying NOT NULL, "source_ip" character varying NOT NULL, "privacy" integer NOT NULL, "type" character varying NOT NULL, "source" character varying, "source_url" character varying, "mediaId" integer, "mediaOriginalId" integer, "subSub" character varying, "organisationId" integer, CONSTRAINT "REL_a7fd6a08e6e5c2b956d88d5d94" UNIQUE ("mediaId"), CONSTRAINT "REL_2c66a758c545e31b9d23ea9b3e" UNIQUE ("mediaOriginalId"), CONSTRAINT "PK_1209d107fe21482beaea51b745e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "experience_tags_tag" ("experienceId" integer NOT NULL, "tagId" integer NOT NULL, CONSTRAINT "PK_a93f32c8822144d9a241f323770" PRIMARY KEY ("experienceId", "tagId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a7db19c4feaa4e9f0fdeb71f66" ON "experience_tags_tag" ("experienceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a093b49b6516643c2fed2d8e2c" ON "experience_tags_tag" ("tagId") `);
        await queryRunner.query(`CREATE TABLE "user_saved_experiences_experience" ("experienceId" integer NOT NULL, "userSub" character varying NOT NULL, CONSTRAINT "PK_5df3908dea36e7f3c8fa085974e" PRIMARY KEY ("experienceId", "userSub"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7e6e7a312dff2693bd1892566b" ON "user_saved_experiences_experience" ("experienceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d4be96eb755a5ed89ce0b857bf" ON "user_saved_experiences_experience" ("userSub") `);
        await queryRunner.query(`CREATE TABLE "experience_attributes_attribute" ("experienceId" integer NOT NULL, "attributeId" integer NOT NULL, CONSTRAINT "PK_f5eae97d9b8cafe633a5b3f137d" PRIMARY KEY ("experienceId", "attributeId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_997335405b7467fa2e80e549a7" ON "experience_attributes_attribute" ("experienceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_55cb0461ba1296e1963abfdc6e" ON "experience_attributes_attribute" ("attributeId") `);
        await queryRunner.query(`CREATE TABLE "asset_tags_asset_tag" ("assetId" integer NOT NULL, "assetTagId" integer NOT NULL, CONSTRAINT "PK_3fdc571079ae84e9e2759a16fad" PRIMARY KEY ("assetId", "assetTagId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dfcf518ac9124609be553928ed" ON "asset_tags_asset_tag" ("assetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f708c8b991f461fde9761c6ed5" ON "asset_tags_asset_tag" ("assetTagId") `);
        await queryRunner.query(`ALTER TABLE "experience_lock" ADD CONSTRAINT "FK_574f16ad51edd8132aa3baa404a" FOREIGN KEY ("experienceId") REFERENCES "experience"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience_lock" ADD CONSTRAINT "FK_b2d560ebce43818ca159968a72f" FOREIGN KEY ("lockedBySub") REFERENCES "user"("sub") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience_share" ADD CONSTRAINT "FK_ef3f7f1259226fc3ebfc8c87f4a" FOREIGN KEY ("experience_id") REFERENCES "experience"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience_share" ADD CONSTRAINT "FK_dc6b94dde198b6e4e4ad2f78dc7" FOREIGN KEY ("shared_to_id") REFERENCES "user"("sub") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience_share" ADD CONSTRAINT "FK_58be7a9ec168d191f5bfbbd7311" FOREIGN KEY ("shared_by_id") REFERENCES "user"("sub") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tag" ADD CONSTRAINT "FK_9b5ab5a11aacc6f19008d8cae98" FOREIGN KEY ("subSub") REFERENCES "user"("sub") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_085b96cf9c98c04b47896d17dca" FOREIGN KEY ("experienceTypeId") REFERENCES "experience_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_d24a12f7deaab90225db0ad278c" FOREIGN KEY ("layoutId") REFERENCES "layout"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_d79874b0f1f412723d276363fd0" FOREIGN KEY ("spaceId") REFERENCES "space"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_acc8baa99c49ef7db9b0bb73994" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_7095715562d576a66b277f9d519" FOREIGN KEY ("screenshot1Id") REFERENCES "media"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_938785766ad154f3ed70586dae2" FOREIGN KEY ("screenshot2Id") REFERENCES "media"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_ded1e2268c84d94743cf60d8756" FOREIGN KEY ("screenshot3Id") REFERENCES "media"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_cf37c077b800be33d6f19b74201" FOREIGN KEY ("screenshot4Id") REFERENCES "media"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_1998a5b58df53b9f44c17ae91b4" FOREIGN KEY ("attachmentId") REFERENCES "media"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_bb15df72ed428a5d3e147226c19" FOREIGN KEY ("subSub") REFERENCES "user"("sub") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience" ADD CONSTRAINT "FK_d9bbc5abcab75a66242b64fa75a" FOREIGN KEY ("organisationId") REFERENCES "organisation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_cd81db2b14bf99eaec0934d1f29" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surface" ADD CONSTRAINT "FK_bcb3ac451d37569acb99f58c5e0" FOREIGN KEY ("subSub") REFERENCES "user"("sub") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surface" ADD CONSTRAINT "FK_6d12e2ac6393edefd9a4173b626" FOREIGN KEY ("layoutId") REFERENCES "layout"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "layout" ADD CONSTRAINT "FK_7e667cf3c19ce14b4c4001a29d3" FOREIGN KEY ("subSub") REFERENCES "user"("sub") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "layout" ADD CONSTRAINT "FK_9b074878ef04eb6067e8650d23e" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "space" ADD CONSTRAINT "FK_07c18a07d58fe9642669d74a8ec" FOREIGN KEY ("layoutId") REFERENCES "layout"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "space" ADD CONSTRAINT "FK_ea45579e2cd497ef265e9d24421" FOREIGN KEY ("subSub") REFERENCES "user"("sub") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "space" ADD CONSTRAINT "FK_6b6638010539f4a5293e2c4d6d3" FOREIGN KEY ("organisationId") REFERENCES "organisation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "space" ADD CONSTRAINT "FK_c8af3f4482bdc5cacfb808a046a" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_ce717bd9411da487be14a091c50" FOREIGN KEY ("subSub") REFERENCES "user"("sub") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_ad42aa1424e15b934dd746c7e29" FOREIGN KEY ("organisationId") REFERENCES "organisation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "template_file" ADD CONSTRAINT "FK_908ab0a2e22b2aba67244a45f23" FOREIGN KEY ("fileId") REFERENCES "media"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "template_file" ADD CONSTRAINT "FK_4205ac5f9516a6c3e4345a347d5" FOREIGN KEY ("subSub") REFERENCES "user"("sub") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "template" ADD CONSTRAINT "FK_678a3f1beca5c93db880148d90e" FOREIGN KEY ("thumbnailId") REFERENCES "media"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "template" ADD CONSTRAINT "FK_d4d548cf8dcf4614ced784690c0" FOREIGN KEY ("templateFileId") REFERENCES "template_file"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "template" ADD CONSTRAINT "FK_0c66ef16947cecf8e029a077186" FOREIGN KEY ("fileId") REFERENCES "media"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "template" ADD CONSTRAINT "FK_d2e66eb50711157bb9b540ed41c" FOREIGN KEY ("subSub") REFERENCES "user"("sub") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_tag" ADD CONSTRAINT "FK_a84c5c4231b1ef6a7c2ebec6f5b" FOREIGN KEY ("subSub") REFERENCES "user"("sub") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset" ADD CONSTRAINT "FK_a7fd6a08e6e5c2b956d88d5d943" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset" ADD CONSTRAINT "FK_2c66a758c545e31b9d23ea9b3ef" FOREIGN KEY ("mediaOriginalId") REFERENCES "media"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset" ADD CONSTRAINT "FK_37cc73641d2d26c6880a7642031" FOREIGN KEY ("subSub") REFERENCES "user"("sub") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset" ADD CONSTRAINT "FK_5cb0293e6d2f45b0682896646f0" FOREIGN KEY ("organisationId") REFERENCES "organisation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experience_tags_tag" ADD CONSTRAINT "FK_a7db19c4feaa4e9f0fdeb71f665" FOREIGN KEY ("experienceId") REFERENCES "experience"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "experience_tags_tag" ADD CONSTRAINT "FK_a093b49b6516643c2fed2d8e2c6" FOREIGN KEY ("tagId") REFERENCES "tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_saved_experiences_experience" ADD CONSTRAINT "FK_7e6e7a312dff2693bd1892566b9" FOREIGN KEY ("experienceId") REFERENCES "experience"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_saved_experiences_experience" ADD CONSTRAINT "FK_d4be96eb755a5ed89ce0b857bfd" FOREIGN KEY ("userSub") REFERENCES "user"("sub") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "experience_attributes_attribute" ADD CONSTRAINT "FK_997335405b7467fa2e80e549a73" FOREIGN KEY ("experienceId") REFERENCES "experience"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "experience_attributes_attribute" ADD CONSTRAINT "FK_55cb0461ba1296e1963abfdc6e2" FOREIGN KEY ("attributeId") REFERENCES "attribute"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "asset_tags_asset_tag" ADD CONSTRAINT "FK_dfcf518ac9124609be553928ed7" FOREIGN KEY ("assetId") REFERENCES "asset"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "asset_tags_asset_tag" ADD CONSTRAINT "FK_f708c8b991f461fde9761c6ed58" FOREIGN KEY ("assetTagId") REFERENCES "asset_tag"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "asset_tags_asset_tag" DROP CONSTRAINT "FK_f708c8b991f461fde9761c6ed58"`);
        await queryRunner.query(`ALTER TABLE "asset_tags_asset_tag" DROP CONSTRAINT "FK_dfcf518ac9124609be553928ed7"`);
        await queryRunner.query(`ALTER TABLE "experience_attributes_attribute" DROP CONSTRAINT "FK_55cb0461ba1296e1963abfdc6e2"`);
        await queryRunner.query(`ALTER TABLE "experience_attributes_attribute" DROP CONSTRAINT "FK_997335405b7467fa2e80e549a73"`);
        await queryRunner.query(`ALTER TABLE "user_saved_experiences_experience" DROP CONSTRAINT "FK_d4be96eb755a5ed89ce0b857bfd"`);
        await queryRunner.query(`ALTER TABLE "user_saved_experiences_experience" DROP CONSTRAINT "FK_7e6e7a312dff2693bd1892566b9"`);
        await queryRunner.query(`ALTER TABLE "experience_tags_tag" DROP CONSTRAINT "FK_a093b49b6516643c2fed2d8e2c6"`);
        await queryRunner.query(`ALTER TABLE "experience_tags_tag" DROP CONSTRAINT "FK_a7db19c4feaa4e9f0fdeb71f665"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP CONSTRAINT "FK_5cb0293e6d2f45b0682896646f0"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP CONSTRAINT "FK_37cc73641d2d26c6880a7642031"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP CONSTRAINT "FK_2c66a758c545e31b9d23ea9b3ef"`);
        await queryRunner.query(`ALTER TABLE "asset" DROP CONSTRAINT "FK_a7fd6a08e6e5c2b956d88d5d943"`);
        await queryRunner.query(`ALTER TABLE "asset_tag" DROP CONSTRAINT "FK_a84c5c4231b1ef6a7c2ebec6f5b"`);
        await queryRunner.query(`ALTER TABLE "template" DROP CONSTRAINT "FK_d2e66eb50711157bb9b540ed41c"`);
        await queryRunner.query(`ALTER TABLE "template" DROP CONSTRAINT "FK_0c66ef16947cecf8e029a077186"`);
        await queryRunner.query(`ALTER TABLE "template" DROP CONSTRAINT "FK_d4d548cf8dcf4614ced784690c0"`);
        await queryRunner.query(`ALTER TABLE "template" DROP CONSTRAINT "FK_678a3f1beca5c93db880148d90e"`);
        await queryRunner.query(`ALTER TABLE "template_file" DROP CONSTRAINT "FK_4205ac5f9516a6c3e4345a347d5"`);
        await queryRunner.query(`ALTER TABLE "template_file" DROP CONSTRAINT "FK_908ab0a2e22b2aba67244a45f23"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_ad42aa1424e15b934dd746c7e29"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_ce717bd9411da487be14a091c50"`);
        await queryRunner.query(`ALTER TABLE "space" DROP CONSTRAINT "FK_c8af3f4482bdc5cacfb808a046a"`);
        await queryRunner.query(`ALTER TABLE "space" DROP CONSTRAINT "FK_6b6638010539f4a5293e2c4d6d3"`);
        await queryRunner.query(`ALTER TABLE "space" DROP CONSTRAINT "FK_ea45579e2cd497ef265e9d24421"`);
        await queryRunner.query(`ALTER TABLE "space" DROP CONSTRAINT "FK_07c18a07d58fe9642669d74a8ec"`);
        await queryRunner.query(`ALTER TABLE "layout" DROP CONSTRAINT "FK_9b074878ef04eb6067e8650d23e"`);
        await queryRunner.query(`ALTER TABLE "layout" DROP CONSTRAINT "FK_7e667cf3c19ce14b4c4001a29d3"`);
        await queryRunner.query(`ALTER TABLE "surface" DROP CONSTRAINT "FK_6d12e2ac6393edefd9a4173b626"`);
        await queryRunner.query(`ALTER TABLE "surface" DROP CONSTRAINT "FK_bcb3ac451d37569acb99f58c5e0"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_cd81db2b14bf99eaec0934d1f29"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_d9bbc5abcab75a66242b64fa75a"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_bb15df72ed428a5d3e147226c19"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_1998a5b58df53b9f44c17ae91b4"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_cf37c077b800be33d6f19b74201"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_ded1e2268c84d94743cf60d8756"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_938785766ad154f3ed70586dae2"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_7095715562d576a66b277f9d519"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_acc8baa99c49ef7db9b0bb73994"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_d79874b0f1f412723d276363fd0"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_d24a12f7deaab90225db0ad278c"`);
        await queryRunner.query(`ALTER TABLE "experience" DROP CONSTRAINT "FK_085b96cf9c98c04b47896d17dca"`);
        await queryRunner.query(`ALTER TABLE "tag" DROP CONSTRAINT "FK_9b5ab5a11aacc6f19008d8cae98"`);
        await queryRunner.query(`ALTER TABLE "experience_share" DROP CONSTRAINT "FK_58be7a9ec168d191f5bfbbd7311"`);
        await queryRunner.query(`ALTER TABLE "experience_share" DROP CONSTRAINT "FK_dc6b94dde198b6e4e4ad2f78dc7"`);
        await queryRunner.query(`ALTER TABLE "experience_share" DROP CONSTRAINT "FK_ef3f7f1259226fc3ebfc8c87f4a"`);
        await queryRunner.query(`ALTER TABLE "experience_lock" DROP CONSTRAINT "FK_b2d560ebce43818ca159968a72f"`);
        await queryRunner.query(`ALTER TABLE "experience_lock" DROP CONSTRAINT "FK_574f16ad51edd8132aa3baa404a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f708c8b991f461fde9761c6ed5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dfcf518ac9124609be553928ed"`);
        await queryRunner.query(`DROP TABLE "asset_tags_asset_tag"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_55cb0461ba1296e1963abfdc6e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_997335405b7467fa2e80e549a7"`);
        await queryRunner.query(`DROP TABLE "experience_attributes_attribute"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d4be96eb755a5ed89ce0b857bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e6e7a312dff2693bd1892566b"`);
        await queryRunner.query(`DROP TABLE "user_saved_experiences_experience"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a093b49b6516643c2fed2d8e2c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7db19c4feaa4e9f0fdeb71f66"`);
        await queryRunner.query(`DROP TABLE "experience_tags_tag"`);
        await queryRunner.query(`DROP TABLE "asset"`);
        await queryRunner.query(`DROP TABLE "asset_tag"`);
        await queryRunner.query(`DROP TABLE "template"`);
        await queryRunner.query(`DROP TABLE "template_file"`);
        await queryRunner.query(`DROP TABLE "media"`);
        await queryRunner.query(`DROP TABLE "organisation"`);
        await queryRunner.query(`DROP TABLE "space"`);
        await queryRunner.query(`DROP TABLE "layout"`);
        await queryRunner.query(`DROP TABLE "surface"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "experience"`);
        await queryRunner.query(`DROP TABLE "attribute"`);
        await queryRunner.query(`DROP TABLE "tag"`);
        await queryRunner.query(`DROP TABLE "experience_share"`);
        await queryRunner.query(`DROP TABLE "experience_type"`);
        await queryRunner.query(`DROP TABLE "experience_lock"`);
    }

}
